# This is a basic workflow to help you get started with Actions

name: CICD

concurrency: production

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  lint:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Setup Node.js environment 14
        uses: actions/setup-node@v2.5.1
        with:
          node-version: 14

      # yarn install & build
      - name: Run yarn install & lint
        run: |
          yarn
          yarn lint

  deploy:
    runs-on: ubuntu-latest

    needs: lint

    steps:
      - name: Deploy to production
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: |
            cd /home/project
            rm -rf my-blog
            git clone git@github.com:wuuli/my-blog.git
            cd my-blog
            yarn install
            yarn build
            pm2 startOrRestart ecosystem.config.js --env production
            pm2 save
